In [5]:
from __future__ import print_function
import os
import numpy as np
import numpy.ma as ma
import Ngl, Nio
from datetime import date, timedelta

In [2]:
f = Nio.open_file("~/Documents/weathe_learn/NCL_draw/wave.nc")
print(f)

Nio file:	wave.nc
   global attributes:
      Conventions : CF-1.6
      history : 2020-01-08 06:06:58 GMT by grib_to_netcdf-2.15.0: /opt/ecmwf/eccodes/bin/grib_to_netcdf -o /cache/data5/adaptor.mars.internal-1578463447.2794712-27712-20-86a99d9a-e07b-47d9-94fc-1242f5433169.nc /cache/tmp/86a99d9a-e07b-47d9-94fc-1242f5433169-adaptor.mars.internal-1578463447.2799587-27712-8-tmp.grib
   dimensions:
      longitude = 720
      latitude = 361
      time = 492
   variables:
      float longitude [ longitude ]
         units :	degrees_east
         long_name :	longitude
      float latitude [ latitude ]
         units :	degrees_north
         long_name :	latitude
      integer time [ time ]
         units :	hours since 1900-01-01 00:00:00.0
         long_name :	time
         calendar :	gregorian
      short p0001 [ time, latitude, longitude ]
         scale_factor :	0.0001015624625834942
         add_offset :	3.361377192724578
         _FillValue :	-32767
         missing_value :	-32767
      

In [3]:
lon = f.variables["longitude"][:]
lat = f.variables["latitude"][:]
w = f.variables["p0001"][1,:,:].data*0.0001015624625834942 + 3.361377192724578

In [4]:
# type(w)

In [5]:
# w.view(ma.MaskedArray)

## Draw

In [6]:
name = "January"
wks_type = "svg"
wks = Ngl.open_wks(wks_type, name)
cnres = Ngl.Resources()

# Contour resources
cnres.cnFillOn        = True
cnres.cnFillPalette   = "WhiteBlueGreenYellowRed"      # New in PyNGL 1.5.0
cnres.cnLinesOn       = False
cnres.cnLineLabelsOn  = False
cnres.cnLevelSpacingF        = 0.5
cnres.cnLevelSelectionMode = "ManualLevels"
cnres.cnMinLevelValF         = 0.5
cnres.cnMaxLevelValF         = 6.5

# Labelbar resource
cnres.lbOrientation   = "horizontal"
cnres.lbLabelFontHeightF  = 0.010

# title
cnres.tiMainString    = name

# Scalar field resources
cnres.sfXArray        = lon[:]
cnres.sfYArray        = lat[:]

# Map resources
cnres.mpFillOn               = True
cnres.mpFillDrawOrder        = "PostDraw"
cnres.mpLandFillColor        = -1
cnres.mpOceanFillColor       = "Transparent"
cnres.mpInlandWaterFillColor = "Transparent"

contour = Ngl.contour_map(wks,w,cnres)

Ngl.end()

NameError: name 'lon' is not defined

In [4]:
f = Nio.open_file("~/Documents/weathe_learn/NCL_draw/wave.nc")
times = f.variables["time"][:]

NameError: name 'Nio' is not defined

In [8]:
time/24

<timed eval>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?


TypeError: 'int' object is not callable

In [9]:
from datetime import date, timedelta

days = time[0]/24              # This may work for floats in general, but using integers
                            #   is more precise (e.g. days = int(9465.0))

start = date(1900,1,1)      # This is the "days since" part

delta = timedelta(days)     # Create a time delta object from the number of days

offset = start + delta      # Add the specified number of days to 1990

print(offset)               # >>>  2015-12-01
print(type(offset)) 

NameError: name 'time' is not defined

In [ ]:
offset.isoformat()[:7]

## Setup

In [7]:
def draw_by_month(time, lat, lon, wave):
    # time is int32
    
    # calculate file name
    days = time/24 
    start = date(1900,1,1)
    delta = timedelta(days)
    offset = start + delta
    name = offset.isoformat()[:7]
    
    wks_type = "svg"
    wks = Ngl.open_wks(wks_type, name)
    cnres = Ngl.Resources()

    # Contour resources
    cnres.cnFillOn        = True
    cnres.cnFillPalette   = "WhiteBlueGreenYellowRed"      # New in PyNGL 1.5.0
    cnres.cnLinesOn       = False
    cnres.cnLineLabelsOn  = False
    cnres.cnLevelSpacingF        = 0.5
    cnres.cnLevelSelectionMode = "ManualLevels"
    cnres.cnMinLevelValF         = 0.5
    cnres.cnMaxLevelValF         = 6.5

    # Labelbar resource
    cnres.lbOrientation   = "horizontal"
    cnres.lbLabelFontHeightF  = 0.010

    # title
    cnres.tiMainString    = name

    # Scalar field resources
    cnres.sfXArray        = lon
    cnres.sfYArray        = lat

    # Map resources
    cnres.mpFillOn               = True
    cnres.mpFillDrawOrder        = "PostDraw"
    cnres.mpLandFillColor        = -1
    cnres.mpOceanFillColor       = "Transparent"
    cnres.mpInlandWaterFillColor = "Transparent"

    contour = Ngl.contour_map(wks,wave,cnres)
    
    Ngl.draw(plot)        # Drawing plot will draw attached text
    Ngl.frame(wks)        # Advance frame

    Ngl.end()

In [10]:
f = Nio.open_file("~/Documents/weathe_learn/NCL_draw/wave.nc")
lon = f.variables["longitude"][:]
lat = f.variables["latitude"][:]
times = f.variables["time"][:]
#wave = f.variables["p0001"][:]

In [11]:
wave_to_draw = wave[1,:,:].data*0.0001015624625834942 + 3.361377192724578
print(wave_to_draw)
draw_by_month(1, lat, lon, wave_to_draw)

[[0.03347998 0.03347998 0.03347998 ... 0.03347998 0.03347998 0.03347998]
 [0.03347998 0.03347998 0.03347998 ... 0.03347998 0.03347998 0.03347998]
 [0.03347998 0.03347998 0.03347998 ... 0.03347998 0.03347998 0.03347998]
 ...
 [0.03347998 0.03347998 0.03347998 ... 0.03347998 0.03347998 0.03347998]
 [0.03347998 0.03347998 0.03347998 ... 0.03347998 0.03347998 0.03347998]
 [0.03347998 0.03347998 0.03347998 ... 0.03347998 0.03347998 0.03347998]]


In [12]:
len(times)

492

In [15]:
wave_index = 0
for time in times[0:5]:
    print(time)
    print(wave_index)
    wave_to_draw  = f.variables["p0001"][wave_index,:,:].data*0.0001015624625834942 + 3.361377192724578
    draw_by_month(time, lat, lon, wave_to_draw)
    wave_index = wave_index +1

692496
0
693240
1
693912
2
694656
3
695376
4


In [3]:
from netCDF4 import Dataset
nc_obj=Dataset('./wave.nc')

In [6]:
print(nc_obj)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    Conventions: CF-1.6
    history: 2020-01-08 06:06:58 GMT by grib_to_netcdf-2.15.0: /opt/ecmwf/eccodes/bin/grib_to_netcdf -o /cache/data5/adaptor.mars.internal-1578463447.2794712-27712-20-86a99d9a-e07b-47d9-94fc-1242f5433169.nc /cache/tmp/86a99d9a-e07b-47d9-94fc-1242f5433169-adaptor.mars.internal-1578463447.2799587-27712-8-tmp.grib
    dimensions(sizes): longitude(720), latitude(361), time(492)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 time(time), int16 p0001(time,latitude,longitude), int16 p0005(time,latitude,longitude)
    groups: 


In [7]:
print(nc_obj.variables.keys())
for i in nc_obj.variables.keys():
    print(i)

dict_keys(['longitude', 'latitude', 'time', 'p0001', 'p0005'])
longitude
latitude
time
p0001
p0005


In [10]:
print(nc_obj.variables['longitude'])
print(nc_obj.variables['latitude'])
print(nc_obj.variables['time'])
print(nc_obj.variables['p0001'])
print(nc_obj.variables['p0005'])

<class 'netCDF4._netCDF4.Variable'>
float32 longitude(longitude)
    units: degrees_east
    long_name: longitude
unlimited dimensions: 
current shape = (720,)
filling on, default _FillValue of 9.969209968386869e+36 used
<class 'netCDF4._netCDF4.Variable'>
float32 latitude(latitude)
    units: degrees_north
    long_name: latitude
unlimited dimensions: 
current shape = (361,)
filling on, default _FillValue of 9.969209968386869e+36 used
<class 'netCDF4._netCDF4.Variable'>
int32 time(time)
    units: hours since 1900-01-01 00:00:00.0
    long_name: time
    calendar: gregorian
unlimited dimensions: 
current shape = (492,)
filling on, default _FillValue of -2147483647 used
<class 'netCDF4._netCDF4.Variable'>
int16 p0001(time, latitude, longitude)
    scale_factor: 0.00010156246258349416
    add_offset: 3.361377192724578
    _FillValue: -32767
    missing_value: -32767
    units: m
    long_name: Significant height of combined wind waves and swell
unlimited dimensions: 
current shape = (49

In [11]:
print(nc_obj.variables['longitude'].ncattrs())

['units', 'long_name']


In [14]:
wave=(nc_obj.variables['p0001'][:])

masked_array(
  data=[[[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [3.361377192724578, 3.361377192724578, 3.361377192724578, ...,
          3.361377192724578, 3.361377192724578, 3.361377192724578],
         [3.361377192724578, 3.361377192724578, 3.361377192724578, ...,
          3.361377192724578, 3.361377192724578, 3.361377192724578],
         [3.361377192724578, 3.361377192724578, 3.3613771927